name: GitHub Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: euthomasmg
          template: classic
          base: header, activity, community, repositories

          # Output
          filename: metrics.svg
          output_action: commit
          output_path: .

          # Plugins
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_ignored: html, css, shell, hack, scss
          plugin_habits: yes
          plugin_activity: yes
