name: GitHub Metrics

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Card 1 - General stats
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: euthomasmg

          filename: metrics-stats.svg
          output_action: commit
          output_path: .

          template: classic
          base: header, activity, community

          plugin_habits: yes
          plugin_activity: yes

      # Card 2 - Languages
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: euthomasmg

          filename: metrics-langs.svg
          output_action: commit
          output_path: .

          template: classic
          base: ""

          plugin_languages: yes
          plugin_languages_ignored: html, css, shell, hack, scss
          plugin_languages_details: percentage
          plugin_languages_limit: 7
